CAMERA = 'picam'
CAMERA_DIRECTORY = '/home/pi/picam'
ONOFF_PATH = CAMERA_DIRECTORY+'/hooks'
CURRENT_RECORDING_PATH = CAMERA_DIRECTORY+'/rec/tmp'
ARCHIVE_RECORDING_PATH = CAMERA_DIRECTORY+'/rec/archive'
VIDEO_CHUNK_LENGTH = 120  # seconds
LOG_FILE = CAMERA_DIRECTORY+'camera.log'
